{"project":"joyent/manta-marlin","branch":"master","topic":"MANTA-3005","id":"Ief67b3d20f49f2fff860e6a251c8655f5ba568ba","number":"710","subject":"MANTA-3006 marlin should adopt moray v2 MANTA-3007 marlin test \"jobMcanceledRequests\" hangs or fails","owner":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"url":"https://cr.joyent.us/710","commitMessage":"MANTA-3006 marlin should adopt moray v2\nMANTA-3007 marlin test \"jobMcanceledRequests\" hangs or fails\n","createdOn":1476724287,"lastUpdated":1478650962,"open":false,"status":"MERGED","comments":[{"timestamp":1476724287,"reviewer":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"message":"Uploaded patch set 1."},{"timestamp":1476724364,"reviewer":{"name":"Joyent Automation","username":"joyent-automation"},"message":"Patch Set 1: CI-Testing+1\n\n\"make check\" passed ok"},{"timestamp":1478548562,"reviewer":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"message":"Uploaded patch set 2."},{"timestamp":1478548619,"reviewer":{"name":"Joyent Automation","username":"joyent-automation"},"message":"Patch Set 2: CI-Testing+1\n\n\"make check\" passed ok"},{"timestamp":1478649688,"reviewer":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"},"message":"Patch Set 2:\n\n(2 comments)"},{"timestamp":1478650226,"reviewer":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"message":"Patch Set 2:\n\n(2 comments)"},{"timestamp":1478650503,"reviewer":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"},"message":"Patch Set 2: Code-Review+1 Integration-Approval+1"},{"timestamp":1478650962,"reviewer":{"name":"Gerrit Code Review","email":"no-reply@cr.joyent.us"},"message":"Change has been successfully merged by David Pacheco"}],"currentPatchSet":{"number":"2","revision":"ef67b3d20f49f2fff860e6a251c8655f5ba568ba","parents":["a7951d8d496427bb1daa895a98adb38371ebed22"],"ref":"refs/changes/10/710/2","uploader":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"createdOn":1478548562,"author":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"isDraft":false,"kind":"REWORK","approvals":[{"type":"CI-Testing","description":"CI-Testing","value":"1","grantedOn":1478548619,"by":{"name":"Joyent Automation","username":"joyent-automation"}},{"type":"Code-Review","description":"Code-Review","value":"1","grantedOn":1478650503,"by":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"}},{"type":"Integration-Approval","description":"Integration-Approval","value":"1","grantedOn":1478650503,"by":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"}},{"type":"SUBM","value":"1","grantedOn":1478650962,"by":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"}}],"comments":[{"file":"common/lib/util.js","line":144,"reviewer":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"},"message":"Do you know why this callback wasn\u0027t invoked in this case before?"},{"file":"common/lib/util.js","line":144,"reviewer":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"message":"I wondered that too, and I could not find a compelling explanation in the source history.  We only get here when we call checkDone() for an error event after having already written out the header.  In that case, I can only guess that since we already got to line 190 (since we wrote the header), we expected that we\u0027d eventually get \u0027end\u0027 or \u0027error\u0027 on the subresponse, and that that would take care of invoking the callback.  As we saw in the example I pasted into the ticket, that didn\u0027t happen here.  (Of course, it still could happen, and that\u0027s why we now need to check if the callback was invoked already.)"},{"file":"dev/tools/test-proxy-upstream.js","line":26,"reviewer":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"},"message":"Is there a reason you changed the port number for this example server?"},{"file":"dev/tools/test-proxy-upstream.js","line":26,"reviewer":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"message":"The port number here is arbitrary.  I thought it would be easier to start from a round number because the new proxy programs end up using the next couple of ports sequentially."}],"files":[{"file":"/COMMIT_MSG","type":"ADDED","insertions":8,"deletions":0},{"file":"common/lib/bus.js","type":"MODIFIED","insertions":2,"deletions":-2},{"file":"common/lib/marlin.js","type":"MODIFIED","insertions":2,"deletions":-2},{"file":"common/lib/util.js","type":"MODIFIED","insertions":18,"deletions":-1},{"file":"dev/package.json","type":"MODIFIED","insertions":1,"deletions":-1},{"file":"dev/tools/test-proxy-proxy.js","type":"MODIFIED","insertions":15,"deletions":-3},{"file":"dev/tools/test-proxy-upstream.js","type":"MODIFIED","insertions":2,"deletions":-2},{"file":"package.json","type":"MODIFIED","insertions":1,"deletions":-1}],"sizeInsertions":41,"sizeDeletions":-12},"patchSets":[{"number":"1","revision":"79d70af8e6efc941a5514e32f55ec129fba7da85","parents":["25eb5ec493e3a8082eddbb9d25eb23d97f466cfd"],"ref":"refs/changes/10/710/1","uploader":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"createdOn":1476724287,"author":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"isDraft":false,"kind":"REWORK","approvals":[{"type":"CI-Testing","description":"CI-Testing","value":"1","grantedOn":1476724364,"by":{"name":"Joyent Automation","username":"joyent-automation"}}],"files":[{"file":"/COMMIT_MSG","type":"ADDED","insertions":7,"deletions":0},{"file":"common/lib/bus.js","type":"MODIFIED","insertions":2,"deletions":-2},{"file":"common/lib/marlin.js","type":"MODIFIED","insertions":2,"deletions":-2},{"file":"dev/package.json","type":"MODIFIED","insertions":1,"deletions":-1},{"file":"package.json","type":"MODIFIED","insertions":1,"deletions":-1}],"sizeInsertions":6,"sizeDeletions":-6},{"number":"2","revision":"ef67b3d20f49f2fff860e6a251c8655f5ba568ba","parents":["a7951d8d496427bb1daa895a98adb38371ebed22"],"ref":"refs/changes/10/710/2","uploader":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"createdOn":1478548562,"author":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"isDraft":false,"kind":"REWORK","approvals":[{"type":"SUBM","value":"1","grantedOn":1478650962,"by":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"}},{"type":"CI-Testing","description":"CI-Testing","value":"1","grantedOn":1478548619,"by":{"name":"Joyent Automation","username":"joyent-automation"}},{"type":"Code-Review","description":"Code-Review","value":"1","grantedOn":1478650503,"by":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"}},{"type":"Integration-Approval","description":"Integration-Approval","value":"1","grantedOn":1478650503,"by":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"}}],"comments":[{"file":"common/lib/util.js","line":144,"reviewer":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"},"message":"Do you know why this callback wasn\u0027t invoked in this case before?"},{"file":"common/lib/util.js","line":144,"reviewer":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"message":"I wondered that too, and I could not find a compelling explanation in the source history.  We only get here when we call checkDone() for an error event after having already written out the header.  In that case, I can only guess that since we already got to line 190 (since we wrote the header), we expected that we\u0027d eventually get \u0027end\u0027 or \u0027error\u0027 on the subresponse, and that that would take care of invoking the callback.  As we saw in the example I pasted into the ticket, that didn\u0027t happen here.  (Of course, it still could happen, and that\u0027s why we now need to check if the callback was invoked already.)"},{"file":"dev/tools/test-proxy-upstream.js","line":26,"reviewer":{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"},"message":"Is there a reason you changed the port number for this example server?"},{"file":"dev/tools/test-proxy-upstream.js","line":26,"reviewer":{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},"message":"The port number here is arbitrary.  I thought it would be easier to start from a round number because the new proxy programs end up using the next couple of ports sequentially."}],"files":[{"file":"/COMMIT_MSG","type":"ADDED","insertions":8,"deletions":0},{"file":"common/lib/bus.js","type":"MODIFIED","insertions":2,"deletions":-2},{"file":"common/lib/marlin.js","type":"MODIFIED","insertions":2,"deletions":-2},{"file":"common/lib/util.js","type":"MODIFIED","insertions":18,"deletions":-1},{"file":"dev/package.json","type":"MODIFIED","insertions":1,"deletions":-1},{"file":"dev/tools/test-proxy-proxy.js","type":"MODIFIED","insertions":15,"deletions":-3},{"file":"dev/tools/test-proxy-upstream.js","type":"MODIFIED","insertions":2,"deletions":-2},{"file":"package.json","type":"MODIFIED","insertions":1,"deletions":-1}],"sizeInsertions":41,"sizeDeletions":-12}],"allReviewers":[{"name":"Joyent Automation","username":"joyent-automation"},{"name":"David Pacheco","email":"dap@joyent.com","username":"davepacheco"},{"name":"Jordan Hendricks","email":"jordan.hendricks@joyent.com","username":"jordanhendricks"}]}