From 1b7d4add2de5bf72982b81a7db2e15679a0b6798 Mon Sep 17 00:00:00 2001
From: Cody Peter Mello <cody.mello@joyent.com>
Date: Tue, 12 Sep 2017 02:53:35 +0000
Subject: [PATCH] MORAY-431 Errors after query has timed out are emitted when
 there are no "error" listeners

---
 test/sql.test.js | 18 ++++++++++++++++++
 1 file changed, 18 insertions(+)

diff --git a/test/sql.test.js b/test/sql.test.js
index b53784c..4e29879 100644
--- a/test/sql.test.js
+++ b/test/sql.test.js
@@ -103,6 +103,24 @@ test('sql - cleanup', function (t) {
     });
 });
 
+test('sql - error after timeout', function (t) {
+    q = c.sql('SELECT pg_sleep(5); SELECT * FROM nonexistent;',
+        [], { timeout: 1 });
+    q.on('error', function (err) {
+        t.ok(VError.hasCauseWithName(err, 'QueryTimeoutError'),
+            'correct error');
+        t.end();
+    });
+    q.on('record', function (r) {
+        t.fail('no row should be returned');
+        t.deepEqual(r, null, 'no row should be returned - value');
+    });
+    q.on('end', function (r) {
+        t.fail('"error" should have been emitted');
+        t.end();
+    });
+});
+
 test('sql - client timeout respected', function (t) {
     q = c.sql('SELECT pg_sleep(5);', [], { timeout: 1000 });
     q.on('error', function (err) {
-- 
2.21.0

